# **Sesión 2:** Calibración de Cámara 📷⚙️

## 0. Preparación

In [68]:
import cv2
print("OpenCV should be 4.8.0.76 Current version:", cv2.__version__)
from typing import List
import numpy as np
import imageio
import cv2
import copy
import glob
import os

OpenCV should be 4.8.0.76 Current version: 4.8.0


## **Apartado A: Calibración de cámara** (derecha e izquierda)

En este apartado se realiza la calibración de dos cámaras de un sistema estereoscópico. Para ello se trabajará con las imágenes de las carpetas ``left`` y ``right``. En primer lugar se trabajará con la carpeta ``left``. Posteriormente, deberá repetir el proceso con las imágenes en la carpeta ``right``. Ambas carpetas contienen imágenes con las que se calibrarán las cámaras. En ellas aparece el patrón de calibración en diferentes posiciones y orientaciones. Estas imágenes serán los datos de entrada.

Los pasos que deberá seguir para calibrar una cámara son:

1. Defina y ejecute el método para cargar imágenes ``load_images()``.
2. Detecte las esquinas de los patrones usando ``cv2.findChessboardCorners()``. Refine las detecciones con ``cv2.cornerSubPix()``.
3. Compruebe que las detecciones son correctas dibujando los resultados con ``cv2.drawChessboardCorners()``.
4. Defina y ejecute el método ``get_chessboard_points(chessboard_shape, dx, dy)`` que proporcione las coordenadas 3D de las esquinas del patrón. El sistema de referencia utilizado deberá estar anclado al propio patrón.
5. Utilice ``cv2.calibrateCamera`` para obtener los parámetros de calibración para la cámara izquierda.

### **Tarea A.1:** Defina y ejecute el método para cargar imágenes ``load_images()``.

In [69]:
def load_images(filenames: List) -> List:
    return [imageio.imread(filename) for filename in filenames]

In [70]:
# TODO Build a list containing the paths of all images from the left camera
base_img_path = os.path.join(os.getcwd(), "../data/left")

imgs_path = [os.path.join(base_img_path, i) for i in os.listdir(base_img_path)]
imgs = load_images(imgs_path)

C:\Users\alpri\AppData\Local\Temp\ipykernel_35268\283608422.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  return [imageio.imread(filename) for filename in filenames]


### **Tarea A.2:** Detecte las esquinas de los patrones usando ``cv2.findChessboardCorners()``. Refine las detecciones con ``cv2.cornerSubPix()``.

In [71]:
# TODO Find corners with cv2.findChessboardCorners()
corners = [cv2.findChessboardCorners(img, (8,6)) for img in imgs]


In [72]:
corners_copy = copy.deepcopy(corners)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.01)

# TODO To refine corner detections with cv2.cornerSubPix() you need to input grayscale images. Build a list containing grayscale images.
imgs_gray = [cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in imgs]

corners_refined = [cv2.cornerSubPix(i, cor[1], (8, 6), (-1, -1), criteria) if cor[0] else [] for i, cor in zip(imgs_gray, corners_copy)]

### **Tarea A.3:** Compruebe que las detecciones son correctas dibujando los resultados con ``cv2.drawChessboardCorners()``

In [73]:
imgs_copy = copy.deepcopy(imgs)

In [74]:
# TODO Use cv2.drawChessboardCorners() to draw the cornes
cv2.imshow("test", cv2.drawChessboardCorners(imgs_copy[2], (8,6), corners_refined[2], corners[2][0]))
cv2.waitKey()

32

In [75]:
# TODO Show images and save when needed

def show_image(img):
    cv2.imshow("Image", img)
    cv2.waitKey()
    cv2.destroyAllWindows()
    
def write_image(img):
    cv2.imwrite(img)

In [76]:
for i, img in enumerate(imgs_copy):
    if corners[i][0]:
        img_proc = cv2.drawChessboardCorners(
            img, (8, 6), corners_refined[i], corners[i][0])
        show_image(img_proc)

### **Tarea A.4:** Defina y ejecute el método ``get_chessboard_points(chessboard_shape, dx, dy)``

In [ ]:
# TODO Design the method. It should return a np.array with np.float32 elements
def get_chessboard_points(chessboard_shape, dx, dy):
    points = []
    for i in range(chessboard_shape[1]):
        for j in range(chessboard_shape[0]):
            points.append([j*dx, i*dy, 0])
    return np.asarray(points, dtype=np.float32)

In [78]:
# TODO You need the points for every image, not just one (consider a list comprehension)
chessboard_points = [get_chessboard_points((8, 6), 30, 30) for _ in range(len(imgs))]
len(chessboard_points)

19

In [79]:
chessboard_points[0]

array([[  0.,   0.,   0.],
       [ 30.,   0.,   0.],
       [ 60.,   0.,   0.],
       [ 90.,   0.,   0.],
       [120.,   0.,   0.],
       [150.,   0.,   0.],
       [180.,   0.,   0.],
       [210.,   0.,   0.],
       [  0.,  30.,   0.],
       [ 30.,  30.,   0.],
       [ 60.,  30.,   0.],
       [ 90.,  30.,   0.],
       [120.,  30.,   0.],
       [150.,  30.,   0.],
       [180.,  30.,   0.],
       [210.,  30.,   0.],
       [  0.,  60.,   0.],
       [ 30.,  60.,   0.],
       [ 60.,  60.,   0.],
       [ 90.,  60.,   0.],
       [120.,  60.,   0.],
       [150.,  60.,   0.],
       [180.,  60.,   0.],
       [210.,  60.,   0.],
       [  0.,  90.,   0.],
       [ 30.,  90.,   0.],
       [ 60.,  90.,   0.],
       [ 90.,  90.,   0.],
       [120.,  90.,   0.],
       [150.,  90.,   0.],
       [180.,  90.,   0.],
       [210.,  90.,   0.],
       [  0., 120.,   0.],
       [ 30., 120.,   0.],
       [ 60., 120.,   0.],
       [ 90., 120.,   0.],
       [120., 120.,   0.],
 

### **Tarea A.5:** Utilice ``cv2.calibrateCamera()`` para obtener los parámetros de calibración para la cámara izquierda

In [80]:
# Filter data and get only those with adequate detections
valid_corners = [cor[1] for cor in corners if cor[0]]
# Convert list to numpy array
valid_corners = np.asarray(valid_corners, dtype=np.float32)

In [81]:
# TODO
rms, intrinsics, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(chessboard_points[1:], valid_corners, imgs_gray[1].shape, None, None)

# Obtain extrinsics
extrinsics = list(map(lambda rvec, tvec: np.hstack((cv2.Rodrigues(rvec)[0], tvec)), rvecs, tvecs))

In [82]:
# Print outputs
print("Intrinsics:\n", intrinsics)
print("Distortion coefficients:\n", dist_coeffs)
print("Root mean squared reprojection error:\n", rms)

Intrinsics:
 [[419.17367971   0.         149.87203903]
 [  0.         420.67532302 128.88566142]
 [  0.           0.           1.        ]]
Distortion coefficients:
 [[ 2.54768634e-02 -3.34669239e+00  4.93017407e-03 -6.84826720e-03
   2.00281255e+01]]
Root mean squared reprojection error:
 0.15307311371562501


### **Pregunta A.1:** Repita el proceso (carga de imágenes, detección y comprobación de esquinas, etc.) para la cámara derecha.

In [83]:
# TODO Homework
base_img_path = os.path.join(os.getcwd(), "../data/right")

imgs_path = [os.path.join(base_img_path, i) for i in os.listdir(base_img_path)]
imgs_right = load_images(imgs_path)

corners_r = [cv2.findChessboardCorners(img, (8, 6)) for img in imgs_right]

corners_copy_r = copy.deepcopy(corners_r)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.01)

# TODO To refine corner detections with cv2.cornerSubPix() you need to input grayscale images. Build a list containing grayscale images.
imgs_gray_r = [cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) for img in imgs_right]

corners_refined_right = [cv2.cornerSubPix(i, cor[1], (8, 6), (-1, -1), criteria)
                   if cor[0] else [] for i, cor in zip(imgs_gray_r, corners_copy_r)]



imgs_copy_right = copy.deepcopy(imgs_right)

for i, img in enumerate(imgs_copy_right):
    if corners_r[i][0]:
        img_proc = cv2.drawChessboardCorners(
            img, (8, 6), corners_refined_right[i], corners_r[i][0])
        show_image(img_proc)

chessboard_points_r = [get_chessboard_points(
    (8, 6), 30, 30) for _ in range(len(imgs_right))]


# Filter data and get only those with adequate detections
valid_corners_r = [cor[1] for cor in corners_r if cor[0]]
# Convert list to numpy array
valid_corners_r = np.asarray(valid_corners_r, dtype=np.float32)


rms, intrinsics, dist_coeffs, rvecs, tvecs = cv2.calibrateCamera(
    chessboard_points_r[1:], valid_corners_r, imgs_gray_r[1].shape, None, None)

# Obtain extrinsics
extrinsics = list(map(lambda rvec, tvec: np.hstack(
    (cv2.Rodrigues(rvec)[0], tvec)), rvecs, tvecs))

C:\Users\alpri\AppData\Local\Temp\ipykernel_35268\283608422.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  return [imageio.imread(filename) for filename in filenames]


In [84]:
print("Intrinsics:\n", intrinsics)
print("Distortion coefficients:\n", dist_coeffs)
print("Root mean squared reprojection error:\n", rms)

Intrinsics:
 [[432.19183597   0.         146.77820875]
 [  0.         435.44775765 137.27781928]
 [  0.           0.           1.        ]]
Distortion coefficients:
 [[-0.11862369 -0.18601104  0.00625041 -0.00822418  1.08945479]]
Root mean squared reprojection error:
 0.20588850620871404


### **Pregunta A.2:** Diferencias entre cv2.findChessboardCorners() y cv2.cornerSubPix()

In [85]:
# TODO Homework

img_proc1 = cv2.drawChessboardCorners(
    imgs_right[0], (8, 6), corners_r[0][1], corners_r[0][0])
show_image(img_proc1)

img_proc2 = cv2.drawChessboardCorners(
            imgs_right[0], (8, 6), corners_refined_right[0], corners_r[0][0])
show_image(img_proc2)


In [86]:
for i in range(len(imgs_right)):
    total_diff = 0
    if corners_r[i][0]:
        for j in range(len(corners_r[i][1])):
            diff = (corners_r[i][1][j] - corners_refined_right[i][j])
            
            l2 = np.sqrt(diff[0][0]**2 + diff[0][1]**2)
            
            total_diff += l2/8*6
    print(total_diff)

5.392625506511702
17.764132674702132
3.886469922178477
4.0096551419711925
3.7502241466218
2.908356305073877
3.8078058683336597
3.2071180807236153
2.668225094168208
3.2168734817177884
3.1316709249083052
3.2824086272403696
3.0618955175684537
3.3364135489950337
0
2.9975456905969113
3.325551215661421
3.388758721141883
6.891781955697032


In [87]:
img_proc1 = cv2.drawChessboardCorners(
    imgs_right[1], (8, 6), corners_r[1][1], corners_r[1][0])
show_image(img_proc1)

img_proc2 = cv2.drawChessboardCorners(
    imgs_right[1], (8, 6), corners_refined_right[1], corners_r[1][0])
show_image(img_proc2)

### **Pregunta A.3:** Número mínimo de imágenes necesarias para calibrar.

In [88]:
# TODO Homework

## **Apartado B: Corrección de distorsión** (ojo de pez)

En este apartado se trabajará en la corrección de la distorsión debido a lentes de ojo de pez. Primero se calibrará una cámara con este tipo de lente, utilizando las imágenes de la carpeta ``fisheye``. Posteriormente se utilizarán estos parámetros de calibración para corregir la distorsión de una de las imágenes de calibración.

Los pasos que deberá seguir para calibrar una cámara con distorsión de ojo de pez son:

1. Reutilice el método ``load_images()`` para cargar las imágenes de la carpeta ``fisheye``.
2. Detecte las equinas procesando las imágenes con los métodos ``cv2.findChessboardCorners()`` y ``cv2.cornerSubPix()``.
3. Reutilice la función ``get_chessboard_points()`` para obtener las coordenadas del tablero.
4. Defina los argumentos para la función de calibración.
5. Calibre con ``cv2.fisheye.calibrate()``

### **Tarea B.1:** Reutilice el método ``load_images()`` para cargar las imágenes de la carpeta ``fisheye``

In [89]:
# TODO Build a list containing the paths of all images from the fisheye camera and load images
base_img_path = os.path.join(os.getcwd(), "../data/fisheye/*.jpg")

fisheye_imgs_path = glob.glob(base_img_path)
fisheye_imgs = load_images(fisheye_imgs_path)

C:\Users\alpri\AppData\Local\Temp\ipykernel_35268\283608422.py:2: DeprecationWarning: Starting with ImageIO v3 the behavior of this function will switch to that of iio.v3.imread. To keep the current behavior (and make this warning disappear) use `import imageio.v2 as imageio` or call `imageio.v2.imread` directly.
  return [imageio.imread(filename) for filename in filenames]


### **Tarea B.2:** Detecte las equinas procesando las imágenes con los métodos ``cv2.findChessboardCorners()`` y ``cv2.cornerSubPix()``.

In [90]:
imgs_corners = []
# Parameters for cv2.cornerSubPix()
subpix_criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER, 30, 0.1)

#TODO Complete the required parts of the loop
for img in fisheye_imgs:
    
    # TODO parse arguments to cv2.findChessboardCorners()
    corners = cv2.findChessboardCorners(img, (7, 6))
    
    # TODO convert image to grayscale to use cv2.cornerSubPix()
    gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    if corners[0]:
        refined_corners = cv2.cornerSubPix(gray_img, corners[1], (3,3), (-1,-1), subpix_criteria)

        # TODO append only those refined_corners with proper detections
        imgs_corners.append(refined_corners)

### **Tarea B.3:** Reutilice la función ``get_chessboard_points()`` para obtener las coordenadas del tablero

In [91]:
# TODO Define the chessboard dimensions and the lenght of the squares (in [mm])
chessboard_dims = (7, 6)
length = 30
# TODO You need the points for every image, not just one (consider a list comprehension)
fisheye_chessboard_points = [get_chessboard_points(chessboard_dims, length, length).reshape(-1, 1, 3) for _ in range(len(imgs_corners))]

### **Tarea B.4:** Defina los argumentos para la calibración

In [92]:
# Parameters for cv2.fisheye.calibrate()
calibration_flags = cv2.fisheye.CALIB_RECOMPUTE_EXTRINSIC+cv2.fisheye.CALIB_FIX_SKEW
intrinsics = np.zeros((3, 3))
distortion = np.zeros((4, 1))
rotations = [np.zeros((1, 1, 3), dtype=np.float64) for _ in imgs_corners]
traslations = [np.zeros((1, 1, 3), dtype=np.float64) for _ in imgs_corners]


### **Tarea B.5:** Calibración

In [93]:
rms2, _, _, _, _ = \
cv2.fisheye.calibrate(fisheye_chessboard_points, imgs_corners, gray_img.shape[::-1], intrinsics, distortion, rotations, traslations, calibration_flags, subpix_criteria)

In [94]:
# Show intrinsic matrix and distortion coefficients values
print(intrinsics)
print(distortion)

[[188.86914026   0.         503.92900347]
 [  0.         185.32638678 373.58044468]
 [  0.           0.           1.        ]]
[[ 0.07734388]
 [ 0.01482361]
 [ 0.02351869]
 [-0.02757565]]


In [95]:
print(rms2)

136.8425931206207


### **Pregunta B.1:** Corrija la distorsión de las 2 primeras imágenes de la carpeta ``fisheye``

In [96]:
# TODO Search in the documentation to define 'dim'
dim = cv2.cvtColor(fisheye_imgs[0], cv2.COLOR_BGR2GRAY).shape[::-1]
map1, map2 = cv2.fisheye.initUndistortRectifyMap(intrinsics, distortion, np.eye(3), intrinsics, dim, cv2.CV_16SC2)

In [97]:
# TODO Homework: correct distortion using cv2.remap()
img = cv2.remap(fisheye_imgs[1], map1, map2, cv2.INTER_LINEAR)
show_image(img)